### ISSUE TITLE
Trouble running example.py

### ISSUE THREAD

**Issue by matiaspereyra777** [IGITUGraz/LSM#2]
Hi. 

I was trying to run the example.py after installing LSM, but I'm getting this error. 
I have tried with python and python3

`----@MonNotebook:~/Documentos/LSM_simulator/LSM_IGITUGraz/LSM-master$ python example.py 

Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import nest
  File "/home/monkho/.local/lib/python2.7/site-packages/nest.py", line 4
    if isinstance(each_item, indent = False ,list):
SyntaxError: non-keyword arg after keyword arg

------@MonNotebook:~/Documentos/LSM_simulator/LSM_IGITUGraz/LSM-master$ python3 example.py 

Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import nest
  File "/home/monkho/.local/lib/python3.6/site-packages/nest.py", line 4
    if isinstance(each_item, indent = False ,list):
                                            ^
SyntaxError: positional argument follows keyword argument
 
`

Any idea of what I may be doing wrong?

Best regards.

**Comment by anandtrex** [comment]
Hi @matiaspereyra777 which version of NEST are you using? It looks like the error is in PyNEST rather than in this package, since the error points to `/home/monkho/.local/lib/python3.6/site-packages/nest.py`. You might want to try out some of the example scripts that come with NEST, and if you get the same problem, file an issue in the [NEST repository](https://github.com/nest/nest-simulator/issues).

**Comment by matiaspereyra777** [comment]
Hi, thank you for your answer!

My version is 1.3.0, it might be the issue. What version should I use?

As you say, that line in _nest.py_ file has an error. I have replaced

`        if isinstance(each_item , indent = False, list): `
with
`        if isinstance(each_item ,list, indent = False):`
because 

> You cannot put a non-keyword argument after a keyword argument

as I read now.

But I have a new error

---/LSM_IGITUGraz/LSM-master$python example.py 

> Traceback (most recent call last):
>   File "example.py", line 119, in <module>
>     main()
>   File "example.py", line 53, in main
>     nest.SetKernelStatus({'print_time': True, 'local_num_threads': 11})
> AttributeError: 'module' object has no attribute 'SetKernelStatus' 
> 

So, a different version should fix the problem.
Regards`

**Comment by anandtrex** [comment]
Hi @matiaspereyra777, I have tested this code with NEST 2.14.0 although I would expect it very likely works with newer versions also.

**Comment by matiaspereyra777** [comment]
Thank you for your help, it works now.

The problem was I using the nest I installed with 

`pip install nest`

After downloading and building the nest 2.14.0, it worked.

Best regards.
