### ISSUE TITLE
about csim-linux-version

### ISSUE THREAD

**Issue by ShirleyGuo** [IGITUGraz/LSM#3]
Dear Authors, 
I tried to install your old LSM implementation, CSim in Ubuntu 18.04, and I followed the user manual, but the command 'install' doesn't work well. The error info is as follows.
make: *** [subdirs] Error 2
Undefined function or variable 'csim'.

Error in install (line 10)
  v=csim('version');

Error in install (line 20)
      install;

I don't know why and there is no clue in the user manual.

**Comment by anandtrex** [comment]
@ShirleyGuo, CSim is not supported anymore by us (It's dependent libraries are too old at this point). We recommend using the NEST/Python version of the LSM code available in this repository.
