### ISSUE TITLE
dimension of lsm

### ISSUE THREAD

**Issue by lslynf** [IGITUGraz/LSM#5]
Dear author:
Thanks for your sharing, I have some questions about the architecture of lsm, the papers I read about the architecture of lsm is three dimensions and the connection weight was set according to the distance between neurons, In this implemention, it likes only has two dimension?

**Comment by anandtrex** [comment]
@lslynf  This code only implements a general liquid state machine, which was used in [this paper](https://iopscience.iop.org/article/10.1088/1748-3190/aa7663/meta). It does not implement the exact model in the original LSM paper.
